---
- name: Install NFS packages (Debian)
  apt:
    name:
      - nfs-kernel-server
      - nfs-common
      - portmap
    state: latest
    install_recommends: no
    update_cache: yes
    cache_valid_time: 86400
  when: ansible_os_family == "Debian"
...

